[project]
name = "mcp-basic-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.59.0",
    "mcp-agent>=0.1.7",
    "mcp[cli]>=1.12.1",
    "openai>=1.97.1",
]
